const nodemailer = require("nodemailer");
const Listing = require("../models/listing");

module.exports.createBooking = async (req, res) => {
  const { id } = req.params;
  const { checkIn, checkOut, totalNights, totalPrice, cardName } = req.body;
  const user = req.user;

  try {
    const listing = await Listing.findById(id);
    if (!listing) {
      return res.status(404).json({ success: false, message: "Listing not found" });
    }

    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS || process.env.EMAIL_USER === "your_gmail@gmail.com") {
      return res.status(500).json({ success: false, message: "Email credentials not configured in .env!" });
    }

    // Email Configuration
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    const mailOptions = {
      from: `"Wanderlust Bookings" <${process.env.EMAIL_USER}>`,
      to: user.email,
      subject: `Booking Confirmation: ${listing.title}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
          <h2 style="color: #ff385c; text-align: center;">Wanderlust</h2>
          <h3 style="text-align: center;">Booking Confirmed!</h3>
          <p>Hi <strong>${user.username}</strong>,</p>
          <p>Thank you for booking with us. Here is your mock payment receipt.</p>
          <hr>
          <h4>Booking Details</h4>
          <p><strong>Property:</strong> ${listing.title}</p>
          <p><strong>Location:</strong> ${listing.location}, ${listing.country}</p>
          <p><strong>Check-in:</strong> ${checkIn}</p>
          <p><strong>Check-out:</strong> ${checkOut}</p>
          <p><strong>Total Nights:</strong> ${totalNights}</p>
          <hr>
          <h4>Payment Summary</h4>
          <p><strong>Billed To:</strong> ${cardName}</p>
          <p style="font-size: 1.2em; color: #198754;"><strong>Total Paid: ₹${Number(totalPrice).toLocaleString("en-IN")}</strong></p>
          <hr>
          <p style="font-size: 0.9em; color: #777;">This is a mock receipt generated by the Wanderlust platform.</p>
        </div>
      `,
    };

    await transporter.sendMail(mailOptions);

    res.json({ success: true, message: "Booking confirmed and email sent!" });
  } catch (err) {
    console.error("Email Error:", err);
    res.status(500).json({ success: false, message: err.message || "Failed to process booking or send email." });
  }
};
